[%s] INFO [<module>:config.py,12] hello
[2019-03-18 17:31:32] INFO [<module>:config.py,12] hello
[2019-03-18 18:13:29] INFO [query:new_db.py,16] None
[2019-03-18 18:14:09] INFO [query:new_db.py,16] None
[2019-03-18 18:15:21] INFO [query:new_db.py,16] select * from user where name = '张三';
[2019-03-18 18:15:21] INFO [query:new_db.py,19] (('张三', '123456'),)
[2019-03-18 18:30:55] DEBUG [_new_conn:connectionpool.py,208] Starting new HTTP connection (1): 115.28.108.130
[2019-03-18 18:30:55] DEBUG [_make_request:connectionpool.py,396] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
[2019-03-18 18:30:55] INFO [test_log_user_login:log_test_user_login.py,25] 测试用例: test_user_login_normal
[2019-03-18 18:30:55] INFO [test_log_user_login:log_test_user_login.py,26] url: http://115.28.108.130:5000/api/user/login/
[2019-03-18 18:30:55] INFO [test_log_user_login:log_test_user_login.py,27] 请求参数: {"name": "张三", "password": "123456"}
[2019-03-18 18:30:55] INFO [test_log_user_login:log_test_user_login.py,28] 预期结果: <h1>登录成功</h1>
[2019-03-18 18:30:55] INFO [test_log_user_login:log_test_user_login.py,29] 实际结果: <h1>登录成功</h1>
[2019-03-18 18:54:37] INFO [log_case_info:case_log.py,7] {'code': '100001', 'data': {'name': '张三', 'password': 'e10adc3949ba59abbe56e057f20f883e'}, 'msg': '失败，用户已存在'}
[2019-03-18 19:02:25] DEBUG [_new_conn:connectionpool.py,208] Starting new HTTP connection (1): 115.28.108.130
[2019-03-18 19:02:25] DEBUG [_make_request:connectionpool.py,396] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 27
[2019-03-18 19:02:25] INFO [log_case_info:case_log.py,10] 测试用例: test_user_login_normal
[2019-03-18 19:02:25] INFO [log_case_info:case_log.py,11] url: http://115.28.108.130:5000/api/user/login/
[2019-03-18 19:02:25] INFO [log_case_info:case_log.py,12] 请求参数: {"name": "张三", "password": "123456"}
[2019-03-18 19:02:25] INFO [log_case_info:case_log.py,13] 预期结果: <h1>登录成功</h1>
[2019-03-18 19:02:25] INFO [log_case_info:case_log.py,14] 实际结果: <h1>请求数据为空</h1>
[2019-03-18 19:02:45] DEBUG [_new_conn:connectionpool.py,208] Starting new HTTP connection (1): 115.28.108.130
[2019-03-18 19:02:45] DEBUG [_make_request:connectionpool.py,396] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 27
[2019-03-18 19:02:45] INFO [log_case_info:case_log.py,10] 测试用例: test_user_login_normal
[2019-03-18 19:02:45] INFO [log_case_info:case_log.py,11] url: http://115.28.108.130:5000/api/user/login/
[2019-03-18 19:02:45] INFO [log_case_info:case_log.py,12] 请求参数: {"name": "张三", "password": "123456"}
[2019-03-18 19:02:45] INFO [log_case_info:case_log.py,13] 预期结果: <h1>登录成功</h1>
[2019-03-18 19:02:45] INFO [log_case_info:case_log.py,14] 实际结果: <h1>请求数据为空</h1>
[2019-03-18 19:03:52] DEBUG [_new_conn:connectionpool.py,208] Starting new HTTP connection (1): 115.28.108.130
[2019-03-18 19:03:52] DEBUG [_make_request:connectionpool.py,396] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
[2019-03-18 19:03:52] INFO [log_case_info:case_log.py,10] 测试用例: test_user_login_normal
[2019-03-18 19:03:52] INFO [log_case_info:case_log.py,11] url: http://115.28.108.130:5000/api/user/login/
[2019-03-18 19:03:52] INFO [log_case_info:case_log.py,12] 请求参数: {"name": "张三", "password": "123456"}
[2019-03-18 19:03:52] INFO [log_case_info:case_log.py,13] 预期结果: <h1>登录成功</h1>
[2019-03-18 19:03:52] INFO [log_case_info:case_log.py,14] 实际结果: <h1>登录成功</h1>
[2019-03-19 09:52:47] DEBUG [_new_conn:connectionpool.py,208] Starting new HTTP connection (1): 115.28.108.130
[2019-03-19 09:52:47] DEBUG [_make_request:connectionpool.py,396] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
[2019-03-19 09:52:47] INFO [log_case_info:case_log.py,10] 测试用例: test_user_login_normal
[2019-03-19 09:52:47] INFO [log_case_info:case_log.py,11] url: http://115.28.108.130:5000/api/user/login/
[2019-03-19 09:52:47] INFO [log_case_info:case_log.py,12] 请求参数: {"name": "张三", "password": "123456"}
[2019-03-19 09:52:47] INFO [log_case_info:case_log.py,13] 预期结果: <h1>登录成功</h1>
[2019-03-19 09:52:47] INFO [log_case_info:case_log.py,14] 实际结果: <h1>登录成功</h1>
